version: '3.6'

services:
  # E-shop DB
  mydb:
    container_name: e-shop-db
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    restart: always
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e-shop
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - e-shop-network
  # phpmyadmin
  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mydb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '127.0.0.1:8000:80'
    environment:
      PMA_HOST: mydb
      MYSQL_ROOT_PASSWORD: root
    networks:
     - e-shop-network
  # e-shop
#  e-shop-server:
#    container_name: eshop
#    depends_on:
#      - mydb
#    image: eimataras/e-shop
#    restart: always
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mydb/e-shop?useSSL=false&allowPublicKeyRetrieval=true
#        - SPRING_DATASOURCE_USERNAME=root
#        - SPRING_DATASOURCE_PASSWORD=root
#    ports:
#      - '8081:8080'
#    networks:
#      - e-shop-network
networks:
  e-shop-network:
volumes:
  data: