version: '3.6'

services:
  # E-shop DB
  mydb:
    container_name: e-shop-db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '127.0.0.1:3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e-shop
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - e-shop-network
  # phpmyadmin
  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mydb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '127.0.0.1:8000:80'
    environment:
      PMA_HOST: mydb
      MYSQL_ROOT_PASSWORD: root
    networks:
     - e-shop-network
  # e-shop
  e-shop-server:
    container_name: eshop
    depends_on:
      - mydb
    image: eimataras/e-shop
    restart: always
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://e-shop-db:3308/e-shop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_VALIDATIONQUERY: SELECT 1
    ports:
      - '8081:8081'
    networks:
      - e-shop-network
networks:
  e-shop-network:
volumes:
  db_data: 